<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%205/1b_Intro_to_NLP_using_TextBlob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TextBlob

Welcome to your hands-on guide to Natural Language Processing ( NLP ) in Python! In this notebook, we will be using NLTK ( the Natural Language Toolkit ) and TextBlob, two of the most popular and user-friendly libraries for working with human language data. Together, they will allow us to break down raw text so a computer can actually understand its structure. You will learn how to clean and normalize words through stemming ( chopping words down to their base form ), identify parts of speech like nouns and verbs ( PoS tagging ), and handle grammatical variations like singularization. Beyond structural analysis, we will also explore sentiment analysis, learning how to computationally detect the emotional undertone of a text to determine if it is positive, negative, or neutral.  The topics presented here will provide a solid foundation in the core pre-processing steps that power everything from search engines to modern AI translation tools.

Documentation for TextBlob can be found [here](https://textblob.readthedocs.io/en/dev/).

In [104]:
%%capture install_output
%%bash

# Install textblob and download corpora
pip install -q -U textblob
pip install -q -U textblob googletrans==4.0.0-rc1 # [cmd+/] When you get to Translation section.
python -m textblob.download_corpora silent

In [105]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import nltk
# from transformers import MarianMTModel, MarianTokenizer
from googletrans import Translator # [cmd+/] When you get to Translation section.

In [3]:
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

## TextBlobs

In [4]:
my_blob = TextBlob("There is more than one way to skin a cat.")

In [5]:
my_blob

TextBlob("There is more than one way to skin a cat.")

## Tagging Parts of Speech
A list of the different parts of speech tags can be found [here](https://www.geeksforgeeks.org/python-part-of-speech-tagging-using-textblob/).

code | meaning | example
--- | --- | ---
CC | coordinating conjunction |
CD | cardinal digit |
DT | determiner |
EX | existential there | (like: "there is" … think of it like "there exists")
FW | foreign word |
IN | preposition/subordinating conjunction |
JJ | adjective | big
JJR | adjective, comparative | bigger
JJS | adjective, superlative | biggest
LS | list marker | 1)
MD | modal could | will
NN | noun, singular | desk
NNS | noun plural | desks
NNP | proper noun, singular | Harrison
NNPS | proper noun, plural | Americans
PDT | predeterminer | all the kids
POS | possessive ending | parents
PRP | personal pronoun | I, he, she
PRP\$ | possessive pronoun | my, his, hers
RB | adverb | very, silently,
RBR | adverb, comparative | better
RBS | adverb, superlative | best
RP | particle | give up
TO | to go | to the store.
UH | interjection | errrrrrrrm
VB | verb, base form | take
VBD | verb, past tense | took
VBG | verb, gerund/present participle | taking
VBN | verb, past participle | taken
VBP | verb, sing. present, non-3d | take
VBZ | verb, 3rd person sing. present | takes
WDT | wh-determiner | which
WP | wh-pronoun | who, what
WP$ | possessive wh-pronoun | whose
WRB | wh-adverb | where, when

In [6]:
#Use the .tags attribute to see parts of speech
my_blob.tags

[('There', 'EX'),
 ('is', 'VBZ'),
 ('more', 'JJR'),
 ('than', 'IN'),
 ('one', 'CD'),
 ('way', 'NN'),
 ('to', 'TO'),
 ('skin', 'VB'),
 ('a', 'DT'),
 ('cat', 'NN')]

In [7]:
pd.DataFrame(my_blob.tags, columns = 'word Pos'.split())

    word  Pos
0  There   EX
1     is  VBZ
2   more  JJR
3   than   IN
4    one   CD
5    way   NN
6     to   TO
7   skin   VB
8      a   DT
9    cat   NN

## Sentiment Analysis

Sentiment analysis can be used to understand the feeling or emotion tied to the text. The sentiment attribute in TextBlob will return two values:
1. The **polarity score** (a float between -1.0 and 1.0). -1 is negative, 1 is positive.
2. The **subjectivity** (a float between 0.0 and 1.0). 0 is very objective, while 1 is very subjective.

In [8]:
neg_blob = TextBlob("I am so tired. Today was a long, hard day.")
neg_blob.sentiment

Sentiment(polarity=-0.24722222222222223, subjectivity=0.5472222222222222)

In [9]:
pos_blob = TextBlob("Today was a great day. I am so happy.")
pos_blob.sentiment

Sentiment(polarity=0.8, subjectivity=0.875)

In [10]:
obj_blob = TextBlob("The cat is gray.")
obj_blob.sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [11]:
subj_blob = TextBlob("The cat is so cute and sweet.")
print(subj_blob.sentiment)
print(subj_blob.sentiment.subjectivity) #Only get the subjectivity

Sentiment(polarity=0.425, subjectivity=0.825)
0.825

Sentiment analysis of multiple sentences

In [12]:
my_poem = TextBlob('''
  Python is a great language to learn.
  You can easily do NLP; it's fab.
  It might take some getting used to.
  But it's definitely more gooder than Matlab.
''')

In [13]:
my_poem

TextBlob("
  Python is a great language to learn.
  You can easily do NLP; it's fab.
  It might take some getting used to.
  But it's definitely more gooder than Matlab.
")

In [14]:
my_poem.sentiment

Sentiment(polarity=0.5777777777777778, subjectivity=0.6944444444444445)

In [15]:
my_poem.sentences

[Sentence("
   Python is a great language to learn."),
 Sentence("You can easily do NLP; it's fab."),
 Sentence("It might take some getting used to."),
 Sentence("But it's definitely more gooder than Matlab.")]

In [16]:
type(my_poem.sentences)

list

In [17]:
for sentence in my_poem.sentences:
  print(sentence.sentiment)

Sentiment(polarity=0.8, subjectivity=0.75)
Sentiment(polarity=0.43333333333333335, subjectivity=0.8333333333333334)
Sentiment(polarity=0.0, subjectivity=0.0)
Sentiment(polarity=0.5, subjectivity=0.5)

### Your Turn
Create three TextBlobs with the following sentiments:
1. Negative, subjective
2. Positive, objective
3. Neutral

In [75]:
# Solution 1 - want pol=-1, subj=1
neg_blob = TextBlob("I am the worst of the worst. Today was a tiresome day.")
neg_blob.sentiment

Sentiment(polarity=-0.8333333333333334, subjectivity=1.0)

In [84]:
# Solution 2 - want pol=1, subj=0
pos_blob = TextBlob("I am excited to type on a computer.")
pos_blob.sentiment

Sentiment(polarity=0.375, subjectivity=0.75)

In [79]:
# Solution 3 - want pol=0, subj=0
obj_blob = TextBlob("The stop sign is red.")
obj_blob.sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

## Tokenization
Tokenization is the process of splitting long strings of text into small pieces (tokens).

In [21]:
my_poem.sentences

[Sentence("
   Python is a great language to learn."),
 Sentence("You can easily do NLP; it's fab."),
 Sentence("It might take some getting used to."),
 Sentence("But it's definitely more gooder than Matlab.")]

In [22]:
my_poem.sentences[0]

Sentence("
  Python is a great language to learn.")

In [23]:
my_poem.sentences[0].words

WordList(['Python', 'is', 'a', 'great', 'language', 'to', 'learn'])

In [24]:
my_poem.words

WordList(['Python', 'is', 'a', 'great', 'language', 'to', 'learn', 'You', 'can', 'easily', 'do', 'NLP', 'it', "'s", 'fab', 'It', 'might', 'take', 'some', 'getting', 'used', 'to', 'But', 'it', "'s", 'definitely', 'more', 'gooder', 'than', 'Matlab'])

In [25]:
(my_poem.word_counts.items())

dict_items([('python', 1), ('is', 1), ('a', 1), ('great', 1), ('language', 1), ('to', 2), ('learn', 1), ('you', 1), ('can', 1), ('easily', 1), ('do', 1), ('nlp', 1), ('it', 3), ('s', 2), ('fab', 1), ('might', 1), ('take', 1), ('some', 1), ('getting', 1), ('used', 1), ('but', 1), ('definitely', 1), ('more', 1), ('gooder', 1), ('than', 1), ('matlab', 1)])

In [26]:
sorted(my_poem.word_counts.items(), key = lambda x: x[1], reverse=True)

[('it', 3),
 ('to', 2),
 ('s', 2),
 ('python', 1),
 ('is', 1),
 ('a', 1),
 ('great', 1),
 ('language', 1),
 ('learn', 1),
 ('you', 1),
 ('can', 1),
 ('easily', 1),
 ('do', 1),
 ('nlp', 1),
 ('fab', 1),
 ('might', 1),
 ('take', 1),
 ('some', 1),
 ('getting', 1),
 ('used', 1),
 ('but', 1),
 ('definitely', 1),
 ('more', 1),
 ('gooder', 1),
 ('than', 1),
 ('matlab', 1)]

In [27]:
pd.Series(my_poem.words).str.lower().str.replace("'","").value_counts()

it            3
to            2
s             2
a             1
is            1
language      1
learn         1
you           1
great         1
python        1
easily        1
can           1
nlp           1
do            1
fab           1
might         1
take          1
some          1
getting       1
used          1
but           1
definitely    1
more          1
gooder        1
than          1
matlab        1
Name: count, dtype: int64

## Singular & Plural

In [28]:
my_sent = TextBlob("The octopi went swimming in the dark ocean waters.")

In [29]:
my_sent.words

WordList(['The', 'octopi', 'went', 'swimming', 'in', 'the', 'dark', 'ocean', 'waters'])

In [30]:
my_sent.words[0]

'The'

In [31]:
#Singularize
my_sent.words[-1].singularize()

'water'

In [32]:
my_sent.words[1].singularize()

'octopus'

In [33]:
#Pluralize
my_sent.words[-2].pluralize()

'oceans'

In [34]:
foo = my_sent.words[-2]
foo == foo.singularize()

True

In [35]:
TextBlob("corpus").words.singularize(), TextBlob("corpus").words.pluralize(), TextBlob("corpus").words.pluralize().singularize()

(WordList(['corpu']), WordList(['corpora']), WordList(['corpus']))

In [36]:
my_sent.words[2:5]

WordList(['went', 'swimming', 'in'])

In [37]:
np.array(my_sent.words)

array(['The', 'octopi', 'went', 'swimming', 'in', 'the', 'dark', 'ocean',
       'waters'], dtype='<U8')

## Stemming & Lemmatization

Stemming is the process of deleting prefixes and suffixes from a word, leaving on the word “stem”. Lemmatization is similar to stemming, but lemmatization is able to capture the underlying meaning of the word.

In [38]:
my_sent

TextBlob("The octopi went swimming in the dark ocean waters.")

In [39]:
#Find the index of 'swimming'
my_sent.words.index('swimming')

3

In [40]:
#Stemming
print(my_sent.words[3].stem())
print(my_sent.words[1].stem())

swim
octopi

In [41]:
#Lemmatization
print(my_sent.words[3].lemmatize())
print(my_sent.words[1].lemmatize())

swimming
octopus

In [42]:
care = TextBlob("caring")

(
  care.words.stem(),
  care.words.lemmatize()
)

(WordList(['care']), WordList(['caring']))

In [43]:
TextBlob("has").words[0].singularize()

'ha'

In [44]:
TextBlob("has").words[0].pluralize()

'hass'

## WordNet

In [45]:
my_sent

TextBlob("The octopi went swimming in the dark ocean waters.")

In [46]:
my_sent.words[-2]

'ocean'

In [47]:
my_sent.words[-2].definitions

['a large body of water constituting a principal part of the hydrosphere',
 'anything apparently limitless in quantity or volume']

In [48]:
{my_sent.words[-2] : my_sent.words[-2].definitions}

{'ocean': ['a large body of water constituting a principal part of the hydrosphere',
  'anything apparently limitless in quantity or volume']}

In [49]:
#Given a set of words, which words are not in my sentence
{"swimming", "tennis"} - set(my_sent.words)

{'tennis'}

In [86]:
TextBlob('has').words[0].singularize().definitions #Extra from lesson

['(astronomy) the angular distance of a celestial point measured westward along the celestial equator from the zenith crossing; the right ascension for an observer at a particular location and time of day']

## Spelling ( correcting )

In [50]:
my_bad_spelling = TextBlob('Helllo, today is my birfday.')
my_bad_spelling.correct()

TextBlob("Hello, today is my birthday.")

In [51]:
[
  f"{x[0]} -> {x[1]}"
    for x in zip(my_bad_spelling.words, my_bad_spelling.correct().words)
      if x[0] != x[1]
]

['Helllo -> Hello', 'birfday -> birthday']

## Counting Words

In [52]:
my_cheer = TextBlob('Data science is the best, data science is the coolest.')
my_cheer.words.count('data')

2

In [53]:
my_cheer.word_counts

defaultdict(int,
            {'data': 2,
             'science': 2,
             'is': 2,
             'the': 2,
             'best': 1,
             'coolest': 1})

### Your Turn
1. Create a TextBlob called `message` and set it equal to `Good morning, todayy is going to be a fantastic day!`.
2. Correct the spelling in your TextBlob and set it equal to a new variable called `message_sp`.
3. Find the index of the word `fantastic`.
4. Look up the definition of the word `fantastic`.
5. Stem and lemmatize the word `fantastic`.

In [88]:
#Solution 1
message = TextBlob('Good morning, todayy is going to be a fantastic day!')

In [89]:
#Solution 2
message_sp = message.correct()
message_sp

TextBlob("Good morning, today is going to be a fantastic day!")

In [96]:
#Solution 3
message_sp.words.index('fantastic')

8

In [99]:
#Solution 4
message_sp.words[8].definitions

['ludicrously odd',
 'extraordinarily good or great ; used especially as intensifiers',
 'fanciful and unrealistic; foolish',
 'existing in fancy only; - Nathaniel Hawthorne',
 'extravagantly fanciful in design, construction, appearance']

In [100]:
#Solution 5
print(message_sp.words[-2].stem())
print(message_sp.words[-2].lemmatize())

fantast
fantastic

## TextBlobs as Strings
TextBlobs act as strings, meaning you can use all of the normal string methods and you can index them as you would a string.

In [59]:
my_cheer

TextBlob("Data science is the best, data science is the coolest.")

In [60]:
my_cheer[0:6]

TextBlob("Data s")

In [61]:
my_cheer.upper()

TextBlob("DATA SCIENCE IS THE BEST, DATA SCIENCE IS THE COOLEST.")

In [62]:
my_cheer.lower()

TextBlob("data science is the best, data science is the coolest.")

## **n**-grams
Overlapping lists of words.

In [63]:
my_cheer

TextBlob("Data science is the best, data science is the coolest.")

In [64]:
my_cheer.words

WordList(['Data', 'science', 'is', 'the', 'best', 'data', 'science', 'is', 'the', 'coolest'])

In [65]:
my_cheer.ngrams(n=3)

[WordList(['Data', 'science', 'is']),
 WordList(['science', 'is', 'the']),
 WordList(['is', 'the', 'best']),
 WordList(['the', 'best', 'data']),
 WordList(['best', 'data', 'science']),
 WordList(['data', 'science', 'is']),
 WordList(['science', 'is', 'the']),
 WordList(['is', 'the', 'coolest'])]

In [66]:
[" ".join(i) for i in my_cheer.ngrams(n=3)]

['Data science is',
 'science is the',
 'is the best',
 'the best data',
 'best data science',
 'data science is',
 'science is the',
 'is the coolest']

In [67]:
my_cheer.split(",")

WordList(['Data science is the best', ' data science is the coolest.'])

In [68]:
my_cheer.words

WordList(['Data', 'science', 'is', 'the', 'best', 'data', 'science', 'is', 'the', 'coolest'])

In [69]:
[" ".join(i) for i in TextBlob("italian pop rock").ngrams(n=2)]

['italian pop', 'pop rock']

## Translation

### Google translate

In [106]:
from googletrans import Translator

In [107]:
translator = Translator()

In [108]:
result = translator.translate(
    'Hello, how are you?',
    src='en',
    dest='es',
)

print(result.text)

¿Hola, cómo estás?

In [109]:
result = translator.translate(
    'Hello, how are you?',
    src='en',
    dest='fr',
)

print(result.text)

Bonjour comment allez-vous?

In [110]:
result = translator.translate(
    'Hello, how are you?',
    src='en',
    dest='ar',
)

print(result.text)

مرحبا، كيف حالك؟

In [111]:
result = translator.translate(
    'Hello, how are you?',
    src='en',
    dest='de',
)

print(result.text)

Hallo, wie geht es dir?

In [112]:
result = translator.translate(
    'Hello, how are you?',
    src='en',
    dest='th',
)

print(result.text)

สวัสดี สบายดีไหม?

In [113]:
result = translator.translate(
    'Hello, how are you?',
    src='en',
    dest='hi',
)

print(result.text)

नमस्ते, आप कैसे हैं?

All in one ...

In [114]:
langs = 'es fr ar de th hi'.split()

for lang in langs:
  result = translator.translate(
      'Hello, how are you?',
      src='en',
      dest=lang,
  )

  print(result.text)

¿Hola, cómo estás?
Bonjour comment allez-vous?
مرحبا، كيف حالك؟
Hallo, wie geht es dir?
สวัสดี สบายดีไหม?
नमस्ते, आप कैसे हैं?

### Hugging Face Transformers (via pre-trained models)

In [115]:
#Load pre-trained MarianMT model
model_name = 'Helsinki-NLP/opus-mt-en-es'
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name, clean_up_tokenization_spaces=True)

text = "Hello, how are you?"
translated = model.generate(**tokenizer(text, return_tensors="pt", padding=True))
result = tokenizer.decode(translated[0], skip_special_tokens=True)

print(result)

NameError: name 'MarianMTModel' is not defined

In [ ]:
#Load pre-trained MarianMT model
model_name = 'Helsinki-NLP/opus-mt-en-fr'
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name, clean_up_tokenization_spaces=True)

text = "Hello, how are you?"
translated = model.generate(**tokenizer(text, return_tensors="pt", padding=True))
result = tokenizer.decode(translated[0], skip_special_tokens=True)

print(result)

In [ ]:
#Load pre-trained MarianMT model
model_name = 'Helsinki-NLP/opus-mt-en-ar'
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name, clean_up_tokenization_spaces=True)

text = "Hello, how are you?"
translated = model.generate(**tokenizer(text, return_tensors="pt", padding=True))
result = tokenizer.decode(translated[0], skip_special_tokens=True)

print(result)

In [ ]:
#Load pre-trained MarianMT model
model_name = 'Helsinki-NLP/opus-mt-en-de'
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name, clean_up_tokenization_spaces=True)

text = "Hello, how are you?"
translated = model.generate(**tokenizer(text, return_tensors="pt", padding=True))
result = tokenizer.decode(translated[0], skip_special_tokens=True)

print(result)