<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%202/4a_Plotly_Express.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Plotly Express documentation can be found [here](https://plotly.com/python/plotly-express/).

In [ ]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

# Gapminder Dataset

In [ ]:
#Example data
gap = px.data.gapminder()
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [ ]:
gap.shape

(1704, 8)

## Line Plot

In [ ]:
#Line Plot
fig = px.line(
    gap,
    x = 'year',
    y = 'lifeExp',
    facet_col = 'continent',
    color = 'country'
)

fig.show()

## Box Plot

In [ ]:
#Box Plot
fig = px.box(
    gap,
    x="year",
    y="lifeExp",
    color="continent",
    notched=True
)

fig.show()

## Scatter Plot

In [ ]:
#Scatter Plot
fig = px.scatter(
    gap,
    x="gdpPercap",
    y="lifeExp",
    size="pop",
    color="continent",
    animation_frame="year",
    hover_name="country",
    log_x=True,
    size_max=60
)

fig.update_yaxes(range=[0, 100])
fig.show()
fig.write_html("gpminder.html")

# fig.write_image("gapminder.svg")

## Map

In [ ]:
fig = px.choropleth(
    gap,
    locations="iso_alpha",
    color="lifeExp",
    hover_name="country",
    animation_frame="year",
    range_color=[20,80]
)

fig.show()

# Iris Dataset

## Scatter Plot w/ Marginal Plots & Trendline

In [ ]:
iris = px.data.iris()
fig = px.scatter(
    iris,
    x="sepal_width",
    y="sepal_length",
    color="species",
    marginal_y="violin",
    marginal_x="box",
    trendline="ols"
)

fig.show()

## Parallel Coordinates Plot

In [ ]:
fig = px.parallel_coordinates(
    iris,
    color="species_id",
    color_continuous_scale=px.colors.diverging.Tealrose,
    color_continuous_midpoint=2
)

fig.show()

## 3D Plot

In [ ]:
fig = px.scatter_3d(
    iris,
    x="sepal_width",
    y="sepal_length",
    z="petal_width",
    color="species_id",
    size="species_id",
    hover_name="species_id"
)

fig.show()

# Carshare Dataset

In [ ]:
cars = px.data.carshare()
cars.head()

   centroid_lat  centroid_lon    car_hours  peak_hour
0     45.471549    -73.588684  1772.750000          2
1     45.543865    -73.562456   986.333333         23
2     45.487640    -73.642767   354.750000         20
3     45.522870    -73.595677   560.166667         23
4     45.453971    -73.738946  2836.666667         19

In [ ]:
cars.shape

(249, 4)

In [ ]:
filter = (cars['peak_hour'] < 5)
cars[filter].groupby('peak_hour')['peak_hour'].count()

peak_hour
0    11
1    15
2    33
3    29
4    17
Name: peak_hour, dtype: int64

## Violin Plot

In [ ]:
cars2 = cars[cars['peak_hour'] < 5]
fig = px.violin(
    cars2,
    y="car_hours",
    x="peak_hour",
    color = 'peak_hour',
    box=True,
    points = 'all',
    hover_data=cars.columns
)

fig.show()

## Map

In [ ]:
fig = px.scatter_mapbox(
        cars,
        lat="centroid_lat",
        lon="centroid_lon",
        color="peak_hour",
        size="car_hours",
        color_continuous_scale=px.colors.cyclical.IceFire,
        size_max=15,
        zoom=10,
        mapbox_style="carto-positron",
        # anima
)

fig.show()

# Start Here

## Your Turn
1. Look at two of the datasets from Plotly Express: `tips` and one other. [List of data sets]( https://plotly.com/python-api-reference/generated/plotly.data.html#module-plotly.data )  There's also a [gallery of plots](https://plotly.com/python/ )
2. Create at least one Plotly Express plot for each of the datasets. Be creative!

### Tips data in a facet plot.

In [ ]:
df = px.data.tips()
df.shape

(244, 7)

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
px.data.tips()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]